### ISSUE TITLE
java.lang.RuntimeException: android.os.TransactionTooLargeException

### ISSUE THREAD

**Issue by Yonjuni** [SecUSo/privacy-friendly-sudoku#22]
```
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1106044 bytes
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3755)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6088)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: android.os.TransactionTooLargeException: data parcel size 1106044 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:615)
	at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3628)
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3747)
	... 7 more
```

**Comment by Yonjuni** [comment]
@Kamuno Could you look into that?

**Comment by Yonjuni** [comment]
Occurs solely on Android 7 and 7.1 devices.
