### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by Yonjuni** [SecUSo/privacy-friendly-sudoku#31]
`
java.lang.RuntimeException: 
  at android.app.LoadedApk.makeApplication(LoadedApk.java:516)
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
  at android.app.ActivityThread.access$1500(ActivityThread.java:139)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1353)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:149)
  at android.app.ActivityThread.main(ActivityThread.java:5257)
  at java.lang.reflect.Method.invokeNative(Native Method:0)
  at java.lang.reflect.Method.invoke(Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:610)
  at dalvik.system.NativeStart.main(Native Method:0)
Caused by: java.lang.IllegalStateException: 
  at android.app.LoadedApk.initializeJavaContextClassLoader(LoadedApk.java:376)
  at android.app.LoadedApk.getClassLoader(LoadedApk.java:329)
  at android.app.LoadedApk.makeApplication(LoadedApk.java:508)
`

**Comment by Kamuno** [comment]
Is there more information about this exception?

**Comment by Yonjuni** [comment]
@Kamuno So far it only occurred on Android 4.4
