### ISSUE TITLE
NullPointer onClick in Tutorial

### ISSUE THREAD

**Issue by Yonjuni** [SecUSo/privacy-friendly-sudoku#33]
`
java.lang.NullPointerException: 
  at org.secuso.privacyfriendlysudoku.ui.TutorialActivity.launchHomeScreen(TutorialActivity.java:133)
  at org.secuso.privacyfriendlysudoku.ui.TutorialActivity.access$000(TutorialActivity.java:30)
  at org.secuso.privacyfriendlysudoku.ui.TutorialActivity$2.onClick(TutorialActivity.java:103)
  at android.view.View.performClick(View.java:5721)
  at android.widget.TextView.performClick(TextView.java:10949)
  at android.view.View$PerformClick.run(View.java:22624)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:148)
  at android.app.ActivityThread.main(ActivityThread.java:7407)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
`

**Comment by Kamuno** [comment]
seems to be already fixed
